### ISSUE TITLE
Release 1.0.2 の zipファイルに macOS用のバイナリデータが含まれていない

### ISSUE THREAD

**Issue by k3nt0w** [Project-PLATEAU/PLATEAU-SDK-for-Unreal#2]
魅力的なSDKの配布ありがとうございます。

[v1.0.2](https://github.com/Project-PLATEAU/PLATEAU-SDK-for-Unreal/releases/tag/v1.0.2) からmacOS用のbuild済みバイナリデータが含まれるように変更されているようですが、手元でDLして展開したところ存在しませんでした。

Windows用のバイナリデータは含まれていたので確認をお願いしたいです。

もし、対応が難しそうであれば手元でbuildできるようにbuild用のドキュメントも記載していただけると助かります。

### 環境

- Apple M1 Max
- 13.3.1（22E261）

**Comment by dazzhe** [comment]
@k3nt0w 
返信遅くなり申し訳ありません。
[v1.2](https://github.com/Project-PLATEAU/PLATEAU-SDK-for-Unreal/releases/tag/v1.2)からMac用のバイナリデータ添付するようにいたしましたので、こちらをご利用ください。

Mac向けのビルド方法はWindowsと同じ方法で出来ますので、[ユーザーマニュアルのインストール手順](https://project-plateau.github.io/PLATEAU-SDK-for-Unreal/manual/Installation.html)をご参照ください。

**Comment by k3nt0w** [comment]
@dazzhe 
対応ありがとうございます。
手元の環境でもう一度試してみます。
