### ISSUE TITLE
インポートの範囲選択で一部が暗い

### ISSUE THREAD

**Issue by 84monta** [Project-PLATEAU/PLATEAU-SDK-for-Unreal#4]
環境
OS：Windows 11 22H2
UE：Unreal Engine 5.2.1
使用SDK：PLATEAU-SDK-for-Unreal-v1.3.0.zip
CPU：AMD Ryzen 7 2700X
GPU：NVIDIA GeForce GTX1080
ローカルに高松のデータをダウンロード

状況
1) 入力フォルダを選択
2) 基準座標系で「04:香川, 愛媛, 徳島, 高知」を選択
3) 範囲選択ボタンをクリック
4) 徐々に地図が表示されるが、画面の上と左側が暗い。

<img width="814" alt="SnapCrab_NoName_2023-6-22_22-1-37_No-00" src="https://github.com/Project-PLATEAU/PLATEAU-SDK-for-Unreal/assets/4171251/567f9791-0a1c-441f-b05f-abd89039daa8">

その他
再現性あり

**Comment by Project-PLATEAU-Admin** [comment]
@84monta 
お手数をおかけしてすみません。
次回のリリース（今月中）に修正される予定です。

**Comment by 84monta** [comment]
昨日、1.3.1で修正されていることを確認しました。
有難うございしました
