### ISSUE TITLE
UE5.2.1ファイルにSDKを適用するとコンパイルエラーで開けない

### ISSUE THREAD

**Issue by rikurikuro** [Project-PLATEAU/PLATEAU-SDK-for-Unreal#5]
UE5.2.1でゲーム→Blankでファイルを作成。編集せず終了し、そのままSDKを導入。
プロジェクトファイルを開こうとするとコンパイルエラーで開けなくなってしまいます。
環境はWindows11, 13世代corei7, RTX 4060(laptop)です。

ファイルがコンパイルエラーで開けなくなるエラーの対処記事やGPT等で数時間試行錯誤しましたが上手くいかず、
もし何か見落としあればご教授いただけると幸いです。
SDKはv1.3.0です。

**Comment by Project-PLATEAU-Admin** [comment]
@rikurikuro 
お手数をおかけしております。
SDKのバージョン、Unreal Engineのバージョン、OS、導入方法は正しいように見えます。
GitHubのリリースにはバイナリが含まれておりますので、通常はビルド不要でプロジェクトを開くことができるはずです。

次のことをご確認いただけないでしょうか。
-  `(プロジェクトフォルダ)/Plugins/PLATEAU-SDK-for-Unreal/Binaries/Win64` 以下にdllファイルがあること、そのようなフォルダ構成になっていること
- プロジェクトフォルダまでのパスが長すぎないこと、パスの長さについてWindowsの上限である260文字まで余裕があること

**Comment by rikurikuro** [comment]
@Project-PLATEAU 
ご連絡頂きありがとうございます。

１点目ですが該当箇所には、
UnrealEditor.modules
UnrealEditor-PLATEAUEditor.pdb
UnrealEditor-PLATEAURuntime.pdb
の３つのファイルのみありました。(SDK v1.3.0)

SDK v1.3.1の場合上記ファイルに加えて、
UnrealEditor-PLATEAUEditorBPLibraries.pdb
UnrealEditor-PLATEAUTests.pdb
の2つが存在していました。

ファイル構造は仰っていただいた通りになっているかと思いますが、
dllファイルは見つかりませんでした。
いずれのバージョンでも同様に起動できず、でした。


２点目ですが、パスの長さは確認しましたが問題ないかと思います。

お手数おかけして申し訳ありません。
よろしくお願いいたします。

**Comment by Project-PLATEAU-Admin** [comment]
@rikurikuro 
情報をくださりありがとうございます。
PLATEAU SDK for Unrealに含まれているはずのdllが消えてしまっているようです。
ウィルス対策ソフト等でDLLを自動削除する設定になっていないかご確認いただければと思います。

**Comment by rikurikuro** [comment]
@Project-PLATEAU 
ご指摘いただいた通り、ウイルス対策ソフトを調整した後に、dllファイルの復活とSDKの起動を無事確認できました。
ご丁寧に教えて頂きましてありがとうございました！
