### ISSUE TITLE
平面直角座標系のエクスポート

### ISSUE THREAD

**Issue by ichi-m** [Project-PLATEAU/PLATEAU-SDK-for-Unreal#6]
SDKでエクスポート時に平面直角座標系を選択し、ENU（PLATEAU）設定で
エクスポートしているのですが、エクスポートしたデータが原点位置のままだと思われます。
これは仕様でしょうか、私の設定ミスでしょうか
平面直角座標位置のまま、エクスポートしたいのです。

Unreal Engine のバージョンは 5.2　です。

**Comment by linoal** [comment]
@ichi-m 
申し訳ございません。  
確認したところ、バグによりエクスポート時の設定を平面直角座標系にしてもローカル座標でエクスポートされてしまうことが判明しました。  
次回のリリースでこのバグは修正予定です。  
お手数をおかけしますが、次のリリースまでの間は、インポート画面で表示される下図の数値をメモしておき、エクスポート後に3DCGソフトを使ってその数値分移動していただければと思います。  
![image](https://github.com/Project-PLATEAU/PLATEAU-SDK-for-Unreal/assets/1321932/b600c142-6766-4edc-9473-ead061d78da1)

**Comment by ichi-m** [comment]
以前のバージョンでは、平面直角座標で設定出来ていたので少し気になっていました。
5.2ではインポート時の数値移動で設定します。
ありがとうございます。

**Comment by linoal** [comment]
@ichi-m 
v2.0.0-alphaをリリースし、修正しました。ご報告ありがとうございました。
